plugins {
    id 'java-library'
}

group = 'not specified'
version = '1.6'

project.ext.lwjglVersion = "3.4.2"
project.ext.currentOs = org.gradle.internal.os.OperatingSystem.current()

project.ext.lwjglNatives = {
    def arch = System.getProperty("os.arch")
    if (project.ext.currentOs.isMacOsX()) {
        return arch.startsWith("aarch64") ? "natives-macos-arm64" : "natives-macos"
    } else if (project.ext.currentOs.isWindows()) {
        return arch.contains("64") ? "natives-windows" : "natives-windows-x86"
    } else if (project.ext.currentOs.isLinux()) {
        return arch.startsWith("aarch64") ? "natives-linux-arm64"
                : arch.startsWith("arm")     ? "natives-linux-arm32"
                : "natives-linux"
    }
    throw new GradleException("Piattaforma non supportata")
}()

repositories {
    mavenCentral()
}

dependencies {
    api platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    api "org.lwjgl:lwjgl"
    api "org.lwjgl:lwjgl-glfw"
    api "org.lwjgl:lwjgl-vulkan"
    api "org.lwjgl:lwjgl-openal"
    api "org.lwjgl:lwjgl-stb"

    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-openal::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"

    implementation 'com.googlecode.soundlibs:mp3spi:1.9.5.4'
    implementation 'com.esotericsoftware:kryo:5.6.2'

    implementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    implementation 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    implementation 'org.junit.jupiter:junit-jupiter-params:5.10.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testClassesDirs = sourceSets.main.output.classesDirs + sourceSets.test.output.classesDirs
    classpath = sourceSets.main.runtimeClasspath + sourceSets.test.runtimeClasspath

    systemProperty 'java.awt.headless', 'true'
    outputs.upToDateWhen { false }

    testLogging {
        events "passed", "failed", "skipped"
        exceptionFormat "full"
        showCauses true
        showExceptions true
        showStackTraces true
    }
}